### ISSUE TITLE
update to support latest linux kernels

### ISSUE THREAD

**Issue by sdwarwick** [PrinzOwO/gtp5g#14]
Linux is currently at 5.8.3,  with ubuntu 18.04 now at version 5.3 and ubuntu 20.04 at version 5.4.   I was wondering what it would take to make this compatible with these kernel versions.  It would be nice not to have to downgrade to 5.0.0.23 when using this in free5GC

**Comment by PrinzOwO** [comment]
Hi,
This repo can make and install with Linux kernel version >= 5.4 now. But in free5GC development, we only test with Linux kernel version 5.0.0-23-generic. Therefore, we could not ensure that the functionality working with free5GC is expected.

Thanks

**Comment by sdwarwick** [comment]
It might be valuable to the community to have this tested with the current versions of Ubuntu,  thanks.

**Comment by muthuramanecs03g** [comment]
@sdwarwick,

There is no action further since Aug 31, 2020.

Could you please update the current status?

**Comment by muthuramanecs03g** [comment]
Hi @sdwarwick,

One more thing, I would like to update you, this repo is part of free5GC project. Now, this repo forked into free5GC and maintain it there only.

https://github.com/free5gc/gtp5g
