### ISSUE TITLE
Does not compile on kernel 5.8

### ISSUE THREAD

**Issue by matsbror** [PrinzOwO/gtp5g#22]
The kernel headers (proc_fs.h) has been changed from 5.4 to 5.8 (do not know when exactly) so that gtp5g does not compile any more.

**Comment by muthuramanecs03g** [comment]
@matsbror,

We didn't verify with the kernel version 5.8.

Could you please pinpoint out the exact error?

**Comment by muthuramanecs03g** [comment]
Hi @matsbror,

Hi @laf0rge,

One more thing, I would like to update you, this repo is part of free5GC project. Now, this repo forked into free5GC and maintain it there only.

https://github.com/free5gc/gtp5g

**Comment by muthuramanecs03g** [comment]
Closing this issue due to no longer support this repo.'

Please, consider opening the issues in https://github.com/free5gc/gtp5g
