### ISSUE TITLE
support Sequence Number 

### ISSUE THREAD

**Issue by yancer** [PrinzOwO/gtp5g#24]
3.2 GTP-U Header Format

   Figure 3 shows general and mandatory GTP-U header and Figure 4 shows
   extension GTP-U header.

   [GTP-U-6]:  GTP-U supports sequence number option in the header, but
               it is not recommended to be used by almost GTP-U
               entities.

   GTP-U header has Sequence Number field to reorder incoming packets
   based on the sequence number.  If Sequence Number Flag is set to '1'
   it indicates that Sequence Number Filed exists in GTP-U header and
   examined at receiving tunnel endpoint node to reorder incoming
   packets.  However, the sequence number flag is set to '1' only for
   RAT HO procedure and sequence number flag should be set to '0' in
   normal case.  Therefore, in normal case receiver tunnel endpoint node
   doesn't examine sequence number and can't reorder GTP-U packets based
   on the sequence number.  This specification is described in section
   5.1 of [TS.29.281-3GPP].

     0                   1                   2                   3
     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
     | Ver |P|R|E|S|N| Message Type|             Length              |
     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
     |                Tunnel Endpoint Identifier                     |
     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
     |      Sequence Number        |   N-PDU Number  |  Next-Ext-Hdr |
     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

                          Figure 3: GTP-U Header

**Comment by muthuramanecs03g** [comment]
@yancer, 

Thanks for sharing the information.

Could you please give me the specification release version?

**Comment by muthuramanecs03g** [comment]
Hi @yancer,

One more thing, I would like to update you, this repo is part of free5GC project. Now, this repo forked into free5GC and maintain it there only.

https://github.com/free5gc/gtp5g

**Comment by muthuramanecs03g** [comment]
Closing this issue due to no longer support this repo.'

Please, consider opening the issues in https://github.com/free5gc/gtp5g
