### ISSUE TITLE
cannot create 5G GTP device : Operation not supported

### ISSUE THREAD

**Issue by dramasamy** [PrinzOwO/gtp5g#25]
Hi Team, thanks for the initiative. I tried gtp-link and gtp-tunnel which doesn't have any problem but while tying gtp5g I see the following, could you let me know the mistake I did?

[root@b0e32fc33a30 gnb]# gtp5g-link add test
cannot create 5G GTP device
: Operation not supported

Linux b0e32fc33a30 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aviweit** [comment]
Hi,
`./gtp5g-link add test` works for me.

It might be that you have an old kernel version (4.15.0-142-generic). I am using Ubuntu 20.04 which comes with 5.4.0-73-generic.

**Comment by muthuramanecs03g** [comment]
@dramasamy,

@aviweit, the comments were right.

Could you please give me the "dmesg" of Linux kernel log?

**Comment by muthuramanecs03g** [comment]
Hi @dramasamy,

One more thing, I would like to update you, this repo is part of free5GC project. Now, this repo forked into free5GC and maintain it there only.

https://github.com/free5gc/gtp5g
