### ISSUE TITLE
get this merged mainline by extending the existing GTP-U kernel support?

### ISSUE THREAD

**Issue by laf0rge** [PrinzOwO/gtp5g#26]
I'm the maintainer of libgtpnl and the existing GTP-U mainline linux kernel module.  It would have been great to see your project discussed one one of our mailing lists.

What are your plans to get this merged mainline?

**Comment by muthuramanecs03g** [comment]
@laf0rge,

We will send a PR to libgtpnl soon.

**Comment by muthuramanecs03g** [comment]
@laf0rge, 

Did you mean merging into Linux Kernel?

**Comment by muthuramanecs03g** [comment]
Hi @laf0rge,

One more thing, I would like to update you, this repo is part of free5GC project. Now, this repo forked into free5GC and maintain it there only.

https://github.com/free5gc/gtp5g
