### ISSUE TITLE
Error when compiling in RHEL7

### ISSUE THREAD

**Issue by robertbotez** [PrinzOwO/gtp5g#29]
Hi,

I tried to compile the module in RHEL7 (kernel version 5.12.10) and I have the following error (I also attached the log file):

/root/gtp5g/gtp5g.c:1461:27: error: ‘ip_tunnel_get_stats64’ undeclared here (not in a function); did you mean ‘ip_tunnel_get_ttl’?
     .ndo_get_stats64    = ip_tunnel_get_stats64,

Does this module support RHEL7?
[log.txt](https://github.com/PrinzOwO/gtp5g/files/6656693/log.txt)

**Comment by muthuramanecs03g** [comment]
Hi @robertbotez ,

>>>Does this module support RHEL7?
No, 

Please consider using and report an issue in the following repository.

https://github.com/free5gc/gtp5g
