### ISSUE TITLE
With kernel 5.4.0-73-generic, gtp5g failed to decap gtp pkts larger than 144 bytes

### ISSUE THREAD

**Issue by mmadnac1313** [PrinzOwO/gtp5g#30]
As title, I have tested it with free5gc, and device "upfgtp" always failed to decap gtp pkts larger than 144 bytes. But it's OK with Linux kernel 5.4.0-42.  
I have printed out "sk_buff->data" to kernel message, and I found  "sk_buff->data" was corrupted since the byte of "next extention header type". Is there any workaround to solve this issue, instead of replacing the kernel?

**Comment by muthuramanecs03g** [comment]
Hi @mmadnac1313,

Which codebase did you use?

This repo no longer to maintain, use the repo https://github.com/free5gc/gtp5g.

Please, consider open an issue in https://github.com/free5gc, and also attach the packet trace of GTP.

**Comment by mmadnac1313** [comment]
HI~muthuramanecs03g ,the repo https://github.com/free5gc/gtp5g. has no "issues" tab, so I am unable to submit the issue.

**Comment by muthuramanecs03g** [comment]
Hi @mmadnac1313 ,

Please, open an issue of gtp5g in UPF repository

https://github.com/free5gc/upf

**Comment by muthuramanecs03g** [comment]
Hi @mmadnac1313,

Wait some time, I will let you know how to open an issue in free5GC/gtp5g.

**Comment by muthuramanecs03g** [comment]
Closing this issue due to no longer support this repo.'

Please, consider opening the issues in https://github.com/free5gc/gtp5g
