### ISSUE TITLE
Failed at make install due to udp_tunnel

### ISSUE THREAD

**Issue by devappforthebest** [PrinzOwO/gtp5g#31]
Currently, I'm try to install modules after already building. When running ```make install``` as root, I get the following error: 
```
modprobe udp_tunnel
modprobe: FATAL: Module udp_tunnel not found in directory 
/lib/modules/5.4.0-77-generic
make: *** [Makefile:20: install] Error 1
```
Could you share with me how to fix this error? (install udp_tunnel module)

**Comment by muthuramanecs03g** [comment]
Hi @devappforthebest ,

This repo no longer to maintain it, use the repo https://github.com/free5gc/gtp5g.
