### ISSUE TITLE
insmod: ERROR: could not insert module gtp5g.ko: Operation not permitted

### ISSUE THREAD

**Issue by kk8421** [PrinzOwO/gtp5g#5]
I can't solve this problem.
I'm using ubuntu 18.04 and  kernel version 5.3.0-53-generic changing to 5.0.0-23-generic.

:~/workspace/gtp5g$ make install
modprobe udp_tunnel
insmod gtp5g.ko
insmod: ERROR: could not insert module gtp5g.ko: Operation not permitted
Makefile:16: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by PrinzOwO** [comment]
Hi @kk8421 ,

You need to run this command with root permission.

1. Use `sudo`
2. Change the user to root

**Comment by kk8421** [comment]
HI @PrinzOwO ,
I have used the root to run.
The issue is not solve.

**Comment by calee0219** [comment]
This may be the same issue, take it a try

https://forum.free5gc.org/t/installation-query-regarding-free5gc/60/5?u=calee

**Comment by kk8421** [comment]
@calee0219 thanks you!
I fellow the step to do, it can solve my problem.
However, I have another problem with free5GC.
I well go to it, and find solution.

**Comment by markman76** [comment]
I solved this issue after disabling the Secure Boot through the BIOS menu.

**Comment by ngovanmao** [comment]
Solved by disabling Secure Boot. following this guide:
https://askubuntu.com/questions/1114867/operation-not-permitted-when-trying-to-modprobe-xpad
