### ISSUE TITLE
Update docs with instructions for compiling `gtp5g` in RHEL8/CentOS8

### ISSUE THREAD

**Issue by williamcaban** [PrinzOwO/gtp5g#6]
# To compile`gtp5g` in RHEL8.2 or CentOS8.x
- Install the Kernel RPMs and elfutils dependencies:
`yum -y install kernel-devel kernel-headers elfutils-libelf elfutils-libelf-devel`

- Update `INCLUDE_DIR` with the CentOS/RHEL 8x Kernel path:
`INCLUDE_DIR = /usr/src/kernels/$(KVERSION)/`

**Comment by muthuramanecs03g** [comment]
@williamcaban,

We didn't prepare the setup like RHEL8.2/CentOS to verify this module.

We will add your comments once the test is done.

Thanks.
